### ISSUE TITLE
Larger version of medical_meadow?

### ISSUE THREAD

**Issue by gameveloster** [kbressem/medAlpaca#19]
Is there a full version of `medical_meadow_small.json` available? Thank you!

**Comment by kbressem** [comment]
Yes. All data used to build the large medical meadow can be found on the HuggingFace repository. If it's not hosted there, I provide links on how to get the data [here](https://github.com/kbressem/medAlpaca/blob/main/DATA_DESCIPTION.md). 

However, you need to merge the different datasets yourself, to build your own large medical meadow.
