### ISSUE TITLE
Error loading 7B weights for medAlpaca

### ISSUE THREAD

**Issue by aadiharan** [kbressem/medAlpaca#23]
Hi!

I've been trying to run the medAlpaca training script based on the example given in the README.md. 

However, I get this error when I load the 7B model : 
 `bias is on the meta device, we need a `value` to put in on 0`

What might be the reason behind this error? And how do we fix this?

Thanks!

System configuration:

GPU : NVIDIA RTX 3080 Ti 24 GB
RAM : 64 GB

Running `medalpaca/train.py` in a virtual environment; all dependencies installed using `requirements.txt` provided.

**Comment by kbressem** [comment]
Can you provide more information, what code you run exactly?
