### ISSUE TITLE
My suggestion for the UI

### ISSUE THREAD

**Issue by ethdig** [kbressem/medAlpaca#24]
**User interface for models:**

**Docker** must be in the game

My suggestion for the UI:
**web interface**
1. **Admin page** (open source, especially **wordpress admin**) where you can install and delete mods and everything else
2. **User registration page**, user login page, and **forum plugin**.
   **To ports 80 (http) and 443 (https)**
**Thank you.**

**Comment by kbressem** [comment]
Thanks for the suggestions. I am not experienced with front end development so the UI is on hold (probably indefinitely). Given there are very good interfaces already, such as the [oobabooga/text-generation-webui](https://github.com/oobabooga/text-generation-webui) I also believe it does not make sense to put out another UI (which will also be much worse than oobabooga's text-generation-webui).
