### ISSUE TITLE
help to run!!!

### ISSUE THREAD

**Issue by ethdig** [kbressem/medAlpaca#26]
these processes are ok,
conda create -n medalpaca python>=3.9
pip install -r requirements.txt

How should I run medAlpaca?

under demo folder: I am running python3 app.py
port 500 opens without any problems, but when I type something in "medAlpaca" I get no response.
Thank you.

**Comment by kbressem** [comment]
We do not really provide a UI, only the models and training scripts. If you only want to try out the model, check out https://github.com/oobabooga/text-generation-webui. You can load the medAlpaca models there as well.

**Comment by ethdig** [comment]
Thank you
