### ISSUE TITLE
How are numbers in the Benchmarks Table Calculated

### ISSUE THREAD

**Issue by KaleabTessera** [kbressem/medAlpaca#33]
So I can see in the eval script where the answers are [generated and stored](https://github.com/kbressem/medAlpaca/blob/8e98505b45c939fa676fd6c81df8f968be292361/eval/eval_usmle.py#L169). I assume some calculation like num_correct/num_questions is done to get the results in the benchmarking table. 

When computing if an answer is correct, do you simply check the starting letter of the answer using regex similiar to [this](https://github.com/kbressem/medAlpaca/blob/8e98505b45c939fa676fd6c81df8f968be292361/eval/eval_usmle.py#L110) or some more sophisticated logic?

**Comment by kbressem** [comment]
I used a combined approach of simple regex and prompting.
I checked if the answer started with a capital letter, if true I checked if the answer was correct. If not I re-asked the model up to 5 times. If asking the model 5 times failed, the answer was set to false.
