### ISSUE TITLE
non-English text getting generated

### ISSUE THREAD

**Issue by hchintada** [kbressem/medAlpaca#38]
Using Huggingface's pipeline with text generation and mode, it is generating a lot of non-English text. Please see below:

![image](https://github.com/kbressem/medAlpaca/assets/19388714/ee43127f-943c-4b3a-9b55-dcc3484e0679)

**Comment by kbressem** [comment]
Strange behavior. My guess is that the OpenAssistant dataset, we used in finetuning, might be the reason for this. This dataset is multilingual. 

During training the model also saw a different prompt template, maybe try to mimic this in your prompting and it will give better results.
