### ISSUE TITLE
training data

### ISSUE THREAD

**Issue by soleiljy** [kbressem/medAlpaca#39]
Hello, 

I would like to retrain other LLMs based on your dataset. It seems like the link to [DATA_DESCRIPTION.md](https://github.com/kbressem/medAlpaca/blob/main/DATA_DESCRIPTION.md) has been broken. 

Where can I get an access to your dataset?

Thanks

**Comment by kbressem** [comment]
the data is on our HuggingFace page, the other datasets should be available online (e.g. medQA).
