### ISSUE TITLE
How to compute scores after USMLE evaluation?

### ISSUE THREAD

**Issue by anonymoususerr1** [kbressem/medAlpaca#40]
Hi, can you share the script to compute the scores after evaluating each model on USMLE data via eval_usmle.py?

**Comment by kbressem** [comment]
I used this notebook. JSON files were created with `eval_usmle.py`. 

[eval_usmle.ipynb.zip](https://github.com/kbressem/medAlpaca/files/12327902/eval_usmle.ipynb.zip)

**Comment by anonymoususerr1** [comment]
With this script. I always get nan as the score for each test. Do you have any idea what this means? Btw, I trained 7b llama 2 models with LoRA on 77k instruction data for 3 epochs.

**Comment by kbressem** [comment]
Does the model fail on some scores and produces nan? I believe if one nan is in the list, numpy will return nan for all.
