### ISSUE TITLE
Stack Exchange HF datasets aren't available

### ISSUE THREAD

**Issue by griff4692** [kbressem/medAlpaca#51]
Could you share the scraping scripts even if you can no longer share the processed data?

Thanks you!

**Comment by SuperBruceJia** [comment]
Mark

**Comment by kbressem** [comment]
Sorry for the rare replies, at the moment I do not find the time to code much. 
My crawler was loosely build on scripts/notebooks from this issue: https://github.com/LAION-AI/Open-Assistant/issues/191

It was a temporary hacked together crawler, which I unfortunately seemed to have removed while cleaning up the local directory. 

However, there are great stack exchange datasets on Hugging Face, which correctly cite the sources and are more complete than my crawl. I would advise against crawling Stack Exchange, just use the HF dataset instead.
